# Generated by Django 3.1 on 2020-08-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200824_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(choices=[('翔泳社', '翔泳社'), ('技術評論社', '技術評論社'), ('SBクリエイティブ', 'SBクリエイティブ'), ('日経BP', '日経BP'), ('秀和システム', '秀和システム')], max_length=50, verbose_name='出版社'),
        ),
    ]
