# Generated by Django 3.1 on 2020-08-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20200824_0800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['the_order']},
        ),
        migrations.AddField(
            model_name='book',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
